# Generated by Django 3.0.4 on 2020-03-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(unique=True)),
                ('post_type_id', models.IntegerField()),
                ('parent_id', models.IntegerField(null=True)),
                ('creation_date', models.DateTimeField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('body', models.TextField(max_length=10000, null=True)),
                ('owner_user_id', models.IntegerField(null=True)),
                ('last_editor_user_id', models.IntegerField(null=True)),
                ('last_edit_date', models.DateTimeField(null=True)),
                ('last_activity_date', models.DateTimeField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
            ],
        ),
    ]
